// CRITICAL ARCHITECTURE TODO: This file is 848 lines - SPLIT IMMEDIATELY into:
// 1. template_generator.go - Template generation logic
// 2. job_implementations.go - Job execution logic
// 3. git_utilities.go - Git helper functions
// 4. template_data_preparation.go - Data preparation logic
//
// TODO: Extract embedded templates to separate files in templates/
// TODO: Implement proper dependency injection instead of direct function calls
// TODO: Create proper error types instead of fmt.Errorf everywhere
// TODO: Implement repository pattern for file operations
// TODO: Use command pattern for jobs instead of massive structs
package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"charm.land/log/v2"
	"github.com/LarsArtmann/GoReleaser-Wizard/cmd/goreleaser-wizard/types"
	"github.com/LarsArtmann/GoReleaser-Wizard/internal/domain"
	"github.com/LarsArtmann/GoReleaser-Wizard/internal/git"
)

const workflowDirPermission = 0o755

// Templates embedded at build time.
const goreleaserTemplateContent = `# GoReleaser configuration
# Generated by goreleaser-wizard
# https://goreleaser.com

version: 2

project_name: {{.ProjectName}}

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...

builds:
  - id: {{.BinaryName}}
    main: {{.MainPath}}
    binary: {{.BinaryName}}
    
    env:
      - CGO_ENABLED={{.CGOEnabled}}
    
    goos:
{{range .Platforms}}      - {{.}}
{{end}}
    goarch:
{{range .Architectures}}      - {{.}}
{{end}}
{{if .IgnoreCombinations}}
    # Ignore certain platform combinations
    ignore:
{{range .IgnoreCombinations}}      - goos: {{.GoOS}}
        goarch: {{.GoArch}}
{{end}}{{end}}
{{if .BuildTags}}
    # Build tags for pure Go builds
    tags:
{{range .BuildTags}}      - {{.}}
{{end}}{{end}}

archives:
  - id: default
    name_template: "{{"{{"}}.ProjectName{{"}}"}}_{{"{{"}}.Version{{"}}"}}_{{"{{"}}.Os{{"}}"}}_{{"{{"}}.Arch{{"}}"}}"
    
    format_overrides:
      - goos: windows
        format: zip
    
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{"{{"}}incpatch .Version{{"}}"}}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "{{"{{"}}.Env.GITHUB_OWNER{{"}}"}}"
    name: "{{"{{"}}.Env.GITHUB_REPO{{"}}"}}"
  
  draft: false
  prerelease: auto
  mode: append
  
  footer: |
    ## Installation
    Download the appropriate archive for your platform from the assets below.

{{if .DockerEnabled}}
dockers:
  - image_templates:
      - "{{.DockerRegistry}}/{{.DockerImage}}:{{"{{"}}.Tag{{"}}"}}"
      - "{{.DockerRegistry}}/{{.DockerImage}}:v{{"{{"}}.Major{{"}}"}}"
      - "{{.DockerRegistry}}/{{.DockerImage}}:latest"
    
    dockerfile: Dockerfile
    
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{"{{"}}.Date{{"}}"}}"
      - "--label=org.opencontainers.image.title={{"{{"}}.ProjectName{{"}}"}}"
      - "--label=org.opencontainers.image.revision={{"{{"}}.FullCommit{{"}}"}}"
      - "--label=org.opencontainers.image.version={{"{{"}}.Version{{"}}"}}"
      - "--platform=linux/amd64"
{{end}}
`

const githubActionsTemplateContent = `name: Release

on:
[[range .Triggers]]  [[.]]
[[end]]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
[[if .DockerEnabled]]
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: [[.DockerRegistry]]
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
[[end]][[if .SigningEnabled]]
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
[[end]]
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
`

// generateGoReleaserConfig generates GoReleaser configuration from SafeProjectConfig.
func generateGoReleaserConfig(config *domain.SafeProjectConfig) error {
	// Validate configuration before generating
	if err := config.Validate(); err != nil {
		return fmt.Errorf("configuration validation failed: %w", err)
	}

	// Generate configuration (state is managed by ConfigGenerationJob)

	// Use embedded template for reliable distribution
	templateContent := goreleaserTemplateContent
	if templateContent == "" {
		return errors.New("embedded GoReleaser template is empty")
	}

	// Create template with custom functions
	tmpl := template.New("goreleaser").Funcs(template.FuncMap{
		"incpatch": git.IncPatchVersion,
	})

	tmpl, err := tmpl.Parse(templateContent)
	if err != nil {
		return fmt.Errorf("failed to parse GoReleaser template: %w", err)
	}

	// Prepare template data
	data := prepareGoReleaserData(config)

	// Generate output
	var output bytes.Buffer
	if err := tmpl.Execute(&output, data); err != nil {
		return fmt.Errorf("failed to execute GoReleaser template: %w", err)
	}

	// Create backup if file exists
	if _, err := os.Stat(".goreleaser.yaml"); err == nil {
		backupPath := ".goreleaser.yaml.backup"

		err := os.Rename(".goreleaser.yaml", backupPath)
		if err != nil {
			return fmt.Errorf("failed to create backup: %w", err)
		}
	}

	// Write generated file
	if err := os.WriteFile(".goreleaser.yaml", output.Bytes(), 0o644); err != nil {
		return fmt.Errorf("failed to write GoReleaser config: %w", err)
	}

	return nil
}

// generateGitHubActions generates GitHub Actions workflow from SafeProjectConfig.
func generateGitHubActions(config *domain.SafeProjectConfig) error {
	// Check if GitHub Actions generation is enabled
	if !config.ShouldGenerateActionsFiles() {
		return errors.New("GitHub Actions generation is not enabled")
	}

	// Use embedded template for reliable distribution
	templateContent := githubActionsTemplateContent
	if templateContent == "" {
		return errors.New("embedded GitHub Actions template is empty")
	}

	// Create template with custom delimiters to avoid GitHub Actions syntax conflict
	tmpl := template.New("github-actions").Delims("[[", "]]")

	tmpl, err := tmpl.Parse(templateContent)
	if err != nil {
		return fmt.Errorf("failed to parse GitHub Actions template: %w", err)
	}

	// Prepare template data
	data := prepareGitHubActionsData(config)

	// Generate output
	var output bytes.Buffer
	if err := tmpl.Execute(&output, data); err != nil {
		return fmt.Errorf("failed to execute GitHub Actions template: %w", err)
	}

	// Ensure .github/workflows directory exists
	workflowDir := filepath.Join(".github", "workflows")
	if err := os.MkdirAll(workflowDir, workflowDirPermission); err != nil {
		return fmt.Errorf("failed to create workflow directory: %w", err)
	}

	// Write generated file
	workflowPath := filepath.Join(workflowDir, "release.yml")
	if err := os.WriteFile(workflowPath, output.Bytes(), 0o644); err != nil {
		return fmt.Errorf("failed to write GitHub Actions workflow: %w", err)
	}

	return nil
}

// ConfigGenerationJob generates GoReleaser configuration.
type ConfigGenerationJob struct {
	id     string
	config *domain.SafeProjectConfig
	force  bool
	logger *log.Logger
}

// NewConfigGenerationJob creates a new config generation job.
func NewConfigGenerationJob(
	config *domain.SafeProjectConfig,
	force bool,
	logger *log.Logger,
) *ConfigGenerationJob {
	return &ConfigGenerationJob{
		id:     "config-generation",
		config: config,
		force:  force,
		logger: logger,
	}
}

func (j *ConfigGenerationJob) ID() string {
	return j.id
}

func (j *ConfigGenerationJob) Name() string {
	return "Generate GoReleaser Configuration"
}

func (j *ConfigGenerationJob) Execute(ctx context.Context) error {
	j.logger.Info("Generating GoReleaser configuration")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return fmt.Errorf("context cancelled: %w", ctx.Err())
	}

	// Transition to Processing state
	j.config.State = domain.ConfigStateProcessing

	// Validate config
	if j.config.ProjectName == "" {
		j.config.State = domain.ConfigStateInvalid

		return errors.New("project name is required")
	}

	// Check existing files
	if !j.force {
		if _, err := os.Stat(".goreleaser.yaml"); err == nil {
			j.config.State = domain.ConfigStateDraft

			return errors.New(".goreleaser.yaml already exists (use --force to overwrite)")
		}
	}

	// Apply defaults to ensure config is complete
	j.config.ApplyDefaults()

	// Generate configuration
	err := generateGoReleaserConfig(j.config)
	if err != nil {
		j.config.State = domain.ConfigStateInvalid

		return fmt.Errorf("failed to generate GoReleaser config: %w", err)
	}

	// Transition to Generated state
	j.config.State = domain.ConfigStateGenerated

	j.logger.Info("GoReleaser configuration generated successfully")

	return nil
}

// GitHubActionsGenerationJob generates GitHub Actions workflow.
type GitHubActionsGenerationJob struct {
	id     string
	config *domain.SafeProjectConfig
	logger *log.Logger
}

// NewGitHubActionsGenerationJob creates a new GitHub Actions generation job.
func NewGitHubActionsGenerationJob(
	config *domain.SafeProjectConfig,
	logger *log.Logger,
) *GitHubActionsGenerationJob {
	return &GitHubActionsGenerationJob{
		id:     "github-actions-generation",
		config: config,
		logger: logger,
	}
}

func (j *GitHubActionsGenerationJob) ID() string {
	return j.id
}

func (j *GitHubActionsGenerationJob) Name() string {
	return "Generate GitHub Actions Workflow"
}

func (j *GitHubActionsGenerationJob) Execute(ctx context.Context) error {
	j.logger.Info("Generating GitHub Actions workflow")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return fmt.Errorf("context cancelled: %w", ctx.Err())
	}

	// Check if GitHub Actions is enabled
	if !j.config.GetGenerateActions() {
		j.logger.Info("GitHub Actions generation is disabled, skipping")

		return nil
	}

	// Create .github/workflows directory
	workflowDir := ".github/workflows"

	err := os.MkdirAll(workflowDir, 0o755)
	if err != nil {
		return fmt.Errorf("failed to create workflow directory: %w", err)
	}

	// Generate workflow
	err = generateGitHubActions(j.config)
	if err != nil {
		return fmt.Errorf("failed to generate GitHub Actions workflow: %w", err)
	}

	j.logger.Info("GitHub Actions workflow generated successfully")

	return nil
}

func (j *GitHubActionsGenerationJob) Rollback(ctx context.Context) error {
	j.logger.Info("Rolling back GitHub Actions workflow generation")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return fmt.Errorf("context cancelled: %w", ctx.Err())
	}

	// Remove generated workflow
	workflowPath := filepath.Join(".github", "workflows", "release.yml")
	if _, err := os.Stat(workflowPath); err == nil {
		err := os.Remove(workflowPath)
		if err != nil {
			j.logger.Errorf("Failed to remove generated workflow: %v", err)

			return fmt.Errorf("failed to remove generated workflow: %w", err)
		}

		j.logger.Info("Removed generated workflow")
	}

	// Try to remove .github directory if empty
	workflowDir := filepath.Join(".github", "workflows")

	workflowFiles, err := filepath.Glob(filepath.Join(workflowDir, "*.yml"))
	if err == nil && len(workflowFiles) == 0 {
		_ = os.Remove(workflowDir)
		_ = os.Remove(".github")
		j.logger.Info("Removed empty .github directory")
	}

	return nil
}

// ProjectValidationJob validates project structure.
type ProjectValidationJob struct {
	id         string
	projectDir string
	logger     *log.Logger
}

// NewProjectValidationJob creates a new project validation job.
func NewProjectValidationJob(projectDir string, logger *log.Logger) *ProjectValidationJob {
	return &ProjectValidationJob{
		id:         "project-validation",
		projectDir: projectDir,
		logger:     logger,
	}
}

func (j *ProjectValidationJob) ID() string {
	return j.id
}

func (j *ProjectValidationJob) Name() string {
	return "Validate Project Structure"
}

func (j *ProjectValidationJob) Execute(ctx context.Context) error {
	j.logger.Info("Validating project structure")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return fmt.Errorf("context cancelled: %w", ctx.Err())
	}

	// Check if project directory exists
	if _, err := os.Stat(j.projectDir); os.IsNotExist(err) {
		return fmt.Errorf("project directory does not exist: %s", j.projectDir)
	}

	// Check for go.mod
	goModPath := filepath.Join(j.projectDir, "go.mod")
	if _, err := os.Stat(goModPath); os.IsNotExist(err) {
		return errors.New("go.mod not found in project directory")
	}

	// Check for main package
	mainPaths := []string{
		filepath.Join(j.projectDir, "main.go"),
		filepath.Join(j.projectDir, "cmd", "*", "main.go"),
	}

	var mainFound bool

	for _, mainPath := range mainPaths {
		matches, err := filepath.Glob(mainPath)
		if err == nil && len(matches) > 0 {
			mainFound = true

			break
		}
	}

	if !mainFound {
		return errors.New("no main.go found in project (expected at main.go or cmd/*/main.go)")
	}

	j.logger.Info("Project structure validation passed")

	return nil
}

func (j *ProjectValidationJob) Rollback(ctx context.Context) error {
	// Validation job doesn't create any files, so rollback is a no-op
	j.logger.Info("Project validation rollback is a no-op")

	return nil
}

// DependencyCheckJob checks for required dependencies.
type DependencyCheckJob struct {
	id           string
	dependencies []string
	logger       *log.Logger
}

// NewDependencyCheckJob creates a new dependency check job.
func NewDependencyCheckJob(dependencies []string, logger *log.Logger) *DependencyCheckJob {
	return &DependencyCheckJob{
		id:           "dependency-check",
		dependencies: dependencies,
		logger:       logger,
	}
}

func (j *DependencyCheckJob) ID() string {
	return j.id
}

func (j *DependencyCheckJob) Name() string {
	return "Check Dependencies"
}

func (j *DependencyCheckJob) Execute(ctx context.Context) error {
	j.logger.Info("Checking dependencies")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return fmt.Errorf("context cancelled: %w", ctx.Err())
	}

	var missingDeps []string

	for _, dep := range j.dependencies {
		path, err := exec.LookPath(dep)
		if err != nil {
			missingDeps = append(missingDeps, dep)
			j.logger.Warnf("Dependency not found: %s", dep)
		} else {
			j.logger.Debugf("Found dependency: %s at %s", dep, path)
		}
	}

	if len(missingDeps) > 0 {
		return fmt.Errorf("missing dependencies: %v", missingDeps)
	}

	j.logger.Info("All dependencies are available")

	return nil
}

func (j *DependencyCheckJob) Rollback(ctx context.Context) error {
	// Dependency check doesn't modify state, so rollback is a no-op
	j.logger.Info("Dependency check rollback is a no-op")

	return nil
}

// JobFactory creates jobs for common wizard operations.
type JobFactory struct {
	logger *log.Logger
}

// NewJobFactory creates a new job factory.
func NewJobFactory(logger *log.Logger) *JobFactory {
	return &JobFactory{
		logger: logger,
	}
}

// CreateFullWizardJobs creates all jobs for a complete wizard operation.
func (jf *JobFactory) CreateFullWizardJobs(config *ProjectConfig, force bool) []Job {
	var jobs []Job

	// Add project validation job
	jobs = append(jobs, NewProjectValidationJob(".", jf.logger))

	// Add dependency check job
	dependencies := []string{"go"}
	if config.GetDockerEnabled() {
		dependencies = append(dependencies, "docker")
	}
	// Only require cosign for advanced signing levels (basic can work without installation)
	if config.SigningLevel == domain.SigningLevelAdvanced ||
		config.SigningLevel == domain.SigningLevelEnterprise {
		dependencies = append(dependencies, "cosign")
	}

	jobs = append(jobs, NewDependencyCheckJob(dependencies, jf.logger))

	// Add config generation job
	jobs = append(jobs, NewConfigGenerationJob(config, force, jf.logger))

	// Add GitHub Actions generation job
	if config.GetGenerateActions() {
		jobs = append(jobs, NewGitHubActionsGenerationJob(config, jf.logger))
	}

	return jobs
}

// prepareGoReleaserData prepares template data for GoReleaser configuration
// CRITICAL TODO: Replace map[string]any with strongly typed structs
// This type safety violation MUST be fixed immediately
//
// TODO: Create proper type-safe template data structures:
// type GoReleaserTemplateData struct { ... }
// type GitHubActionsTemplateData struct { ... }
//
// TODO: Eliminate all map[string]any usage - this is unacceptable
// TODO: Make impossible states unrepresentable through strong types
// TODO: Use proper enums instead of string types throughout.
func prepareGoReleaserData(config *domain.SafeProjectConfig) map[string]any {
	// Get version info
	version := getVersion()

	data := map[string]any{
		"ProjectName": config.ProjectName,
		"BinaryName":  config.BinaryName,
		"MainPath":    config.MainPath,
		"Version":     version,
		"Tag":         version,
		"Major":       git.GetMajorVersion(version),
		"Date":        git.GetCurrentDate(),
		"FullCommit":  getCommitHash(),
		"CGOEnabled": map[domain.CGOStatus]string{
			domain.CGOStatusDisabled: "0",
			domain.CGOStatusEnabled:  "1",
			domain.CGOStatusRequired: "1",
		}[config.CGOStatus],
		"DockerEnabled":  config.DockerSupport.IsEnabled(),
		"SigningEnabled": config.SigningLevel.IsEnabled(),

		// Environment variables for GitHub integration
		"Env": map[string]string{
			"GITHUB_OWNER": types.GetGitHubOwner(),
			"GITHUB_REPO":  types.GetGitHubRepo(),
		},

		// Platform/Arch combinations for archive naming
		"Os":   "{{.Os}}",   // This gets replaced in the template loop
		"Arch": "{{.Arch}}", // This gets replaced in the template loop
	}

	// Convert platforms
	if len(config.Platforms) > 0 {
		platforms := make([]string, len(config.Platforms))
		for i, platform := range config.Platforms {
			platforms[i] = string(platform) // Use raw constant value
		}

		data["Platforms"] = platforms
	}

	// Convert architectures
	if len(config.Architectures) > 0 {
		architectures := make([]string, len(config.Architectures))
		for i, arch := range config.Architectures {
			architectures[i] = string(arch) // Use raw constant value
		}

		data["Architectures"] = architectures
	}

	// Convert build tags
	if len(config.BuildTags) > 0 {
		tags := make([]string, len(config.BuildTags))
		for i, tag := range config.BuildTags {
			tags[i] = tag.String()
		}

		data["BuildTags"] = tags
	}

	// Add ignore combinations (common ones)
	data["IgnoreCombinations"] = []map[string]string{
		{"GoOS": "darwin", "GoArch": "386"},
		{"GoOS": "windows", "GoArch": "arm64"},
	}

	// Add Docker configuration if enabled
	if config.DockerSupport.IsEnabled() {
		data["DockerRegistry"] = config.DockerRegistry.GetURL()
		data["DockerImage"] = config.GetDockerImageName()
	}

	return data
}

// prepareGitHubActionsData prepares template data for GitHub Actions workflow
// CRITICAL TODO: Replace map[string]any with strongly typed structs
// TODO: Create GitHubActionsTemplateData struct with proper field types
// TODO: Validate all data at compile-time instead of runtime.
func prepareGitHubActionsData(config *domain.SafeProjectConfig) map[string]any {
	data := map[string]any{
		"ProjectName":    config.ProjectName,
		"DockerEnabled":  config.DockerSupport.IsEnabled(),
		"SigningEnabled": config.SigningLevel.IsEnabled(),
	}

	// Convert action triggers to GitHub patterns
	if len(config.ActionsOn) > 0 {
		triggers := make([]string, len(config.ActionsOn))
		for i, trigger := range config.ActionsOn {
			triggers[i] = trigger.GitHubPattern()
		}

		data["Triggers"] = triggers
	}

	// Add Docker configuration if enabled
	if config.DockerSupport.IsEnabled() {
		data["DockerRegistry"] = config.DockerRegistry.GetURL()
		data["DockerImage"] = config.GetDockerImageName()
	}

	return data
}

// CreateConfigOnlyJobs creates jobs for config generation only.
func (jf *JobFactory) CreateConfigOnlyJobs(config *ProjectConfig, force bool) []Job {
	return []Job{
		NewProjectValidationJob(".", jf.logger),
		NewConfigGenerationJob(config, force, jf.logger),
	}
}

// CreateValidationOnlyJob creates a validation-only job.
func (jf *JobFactory) CreateValidationOnlyJob(projectDir string) Job {
	return NewProjectValidationJob(projectDir, jf.logger)
}

// Helper functions for template data

// getVersion gets the current version from git or fallback.
func getVersion() string {
	// Try to get version from git
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if cmd := exec.CommandContext(
		ctx,
		"git",
		"describe",
		"--tags",
		"--always",
		"--dirty",
	); cmd != nil {
		if output, err := cmd.Output(); err == nil {
			if version := strings.TrimSpace(string(output)); version != "" {
				return version
			}
		}
	}

	// Fallback to version from build-time variable
	if version != "dev" {
		return version
	}

	// Final fallback
	return "v0.1.0"
}

// getCommitHash gets the current git commit hash.
func getCommitHash() string {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if cmd := exec.CommandContext(ctx, "git", "rev-parse", "HEAD"); cmd != nil {
		if output, err := cmd.Output(); err == nil {
			if hash := strings.TrimSpace(string(output)); hash != "" {
				return hash
			}
		}
	}

	return "unknown"
}
