package main

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/LarsArtmann/GoReleaser-Wizard/internal/domain"
	"github.com/charmbracelet/log"
)

// Templates embedded at build time
const goreleaserTemplateContent = `# GoReleaser configuration
# Generated by goreleaser-wizard
# https://goreleaser.com

version: 2

project_name: {{.ProjectName}}

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...

builds:
  - id: {{.BinaryName}}
    main: {{.MainPath}}
    binary: {{.BinaryName}}
    
    env:
      - CGO_ENABLED={{.CGOEnabled}}
    
    goos:
{{range .Platforms}}      - {{.}}
{{end}}
    goarch:
{{range .Architectures}}      - {{.}}
{{end}}
{{if .IgnoreCombinations}}
    # Ignore certain platform combinations
    ignore:
{{range .IgnoreCombinations}}      - goos: {{.GoOS}}
        goarch: {{.GoArch}}
{{end}}{{end}}
{{if .BuildTags}}
    # Build tags for pure Go builds
    tags:
{{range .BuildTags}}      - {{.}}
{{end}}{{end}}

archives:
  - id: default
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    
    format_overrides:
      - goos: windows
        format: zip
    
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{incpatch .Version}}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "{{.Env.GITHUB_OWNER}}"
    name: "{{.Env.GITHUB_REPO}}"
  
  draft: false
  prerelease: auto
  mode: append
  
  footer: |
    ## Installation
    Download the appropriate archive for your platform from the assets below.

{{if .DockerEnabled}}
dockers:
  - image_templates:
      - "{{.DockerRegistry}}/{{.DockerImage}}:{{.Tag}}"
      - "{{.DockerRegistry}}/{{.DockerImage}}:v{{.Major}}"
      - "{{.DockerRegistry}}/{{.DockerImage}}:latest"
    
    dockerfile: Dockerfile
    
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
{{end}}
`

const githubActionsTemplateContent = `name: Release

on:
[[range .Triggers]]  [[.]]
[[end]]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
[[if .DockerEnabled]]
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: [[.DockerRegistry]]
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
[[end]][[if .SigningEnabled]]
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
[[end]]
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
`

// generateGoReleaserConfig generates GoReleaser configuration from SafeProjectConfig
func generateGoReleaserConfig(config *domain.SafeProjectConfig) error {
	// Generate configuration (state is managed by ConfigGenerationJob)

	// Use embedded template for reliable distribution
	templateContent := goreleaserTemplateContent
	if templateContent == "" {
		return fmt.Errorf("embedded GoReleaser template is empty")
	}

	// Create template with custom functions
	tmpl := template.New("goreleaser").Funcs(template.FuncMap{
		"incpatch": func(v string) string {
			// Simple version increment - remove 'v' prefix and increment patch
			if strings.HasPrefix(v, "v") {
				v = v[1:]
			}
			parts := strings.Split(v, ".")
			if len(parts) == 3 {
				// Convert patch to int and increment
				patch := 0
				if len(parts) > 2 {
					if p, err := fmt.Sscanf(parts[2], "%d", &patch); err == nil && p == 1 {
						return fmt.Sprintf("v%s.%s.%d-next", parts[0], parts[1], patch+1)
					}
				}
			}
			return v + "-next"
		},
	})

	tmpl, err := tmpl.Parse(templateContent)
	if err != nil {
		return fmt.Errorf("failed to parse GoReleaser template: %w", err)
	}

	// Prepare template data
	data := prepareGoReleaserData(config)

	// Generate output
	var output bytes.Buffer
	if err := tmpl.Execute(&output, data); err != nil {
		return fmt.Errorf("failed to execute GoReleaser template: %w", err)
	}

	// Create backup if file exists
	if _, err := os.Stat(".goreleaser.yaml"); err == nil {
		backupPath := ".goreleaser.yaml.backup"
		if err := os.Rename(".goreleaser.yaml", backupPath); err != nil {
			return fmt.Errorf("failed to create backup: %w", err)
		}
	}

	// Write generated file
	if err := os.WriteFile(".goreleaser.yaml", output.Bytes(), 0o644); err != nil {
		return fmt.Errorf("failed to write GoReleaser config: %w", err)
	}

	return nil
}

// generateGitHubActions generates GitHub Actions workflow from SafeProjectConfig
func generateGitHubActions(config *domain.SafeProjectConfig) error {
	// Check if GitHub Actions generation is enabled
	if !config.ShouldGenerateActionsFiles() {
		return fmt.Errorf("GitHub Actions generation is not enabled")
	}

	// Use embedded template for reliable distribution
	templateContent := githubActionsTemplateContent
	if templateContent == "" {
		return fmt.Errorf("embedded GitHub Actions template is empty")
	}

	// Create template with custom delimiters to avoid GitHub Actions syntax conflict
	tmpl := template.New("github-actions").Delims("[[", "]]")

	tmpl, err := tmpl.Parse(templateContent)
	if err != nil {
		return fmt.Errorf("failed to parse GitHub Actions template: %w", err)
	}

	// Prepare template data
	data := prepareGitHubActionsData(config)

	// Generate output
	var output bytes.Buffer
	if err := tmpl.Execute(&output, data); err != nil {
		return fmt.Errorf("failed to execute GitHub Actions template: %w", err)
	}

	// Ensure .github/workflows directory exists
	workflowDir := filepath.Join(".github", "workflows")
	if err := os.MkdirAll(workflowDir, 0o755); err != nil {
		return fmt.Errorf("failed to create workflow directory: %w", err)
	}

	// Write generated file
	workflowPath := filepath.Join(workflowDir, "release.yml")
	if err := os.WriteFile(workflowPath, output.Bytes(), 0o644); err != nil {
		return fmt.Errorf("failed to write GitHub Actions workflow: %w", err)
	}

	return nil
}

// ConfigGenerationJob generates GoReleaser configuration
type ConfigGenerationJob struct {
	id     string
	config *domain.SafeProjectConfig
	force  bool
	logger *log.Logger
}

// NewConfigGenerationJob creates a new config generation job
func NewConfigGenerationJob(config *domain.SafeProjectConfig, force bool, logger *log.Logger) *ConfigGenerationJob {
	return &ConfigGenerationJob{
		id:     "config-generation",
		config: config,
		force:  force,
		logger: logger,
	}
}

func (j *ConfigGenerationJob) ID() string {
	return j.id
}

func (j *ConfigGenerationJob) Name() string {
	return "Generate GoReleaser Configuration"
}

func (j *ConfigGenerationJob) Execute(ctx context.Context) error {
	j.logger.Info("Generating GoReleaser configuration")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return ctx.Err()
	}

	// Transition to Processing state
	j.config.State = domain.ConfigStateProcessing

	// Validate config
	if j.config.ProjectName == "" {
		j.config.State = domain.ConfigStateInvalid
		return fmt.Errorf("project name is required")
	}

	// Check existing files
	if !j.force {
		if _, err := os.Stat(".goreleaser.yaml"); err == nil {
			j.config.State = domain.ConfigStateDraft
			return fmt.Errorf(".goreleaser.yaml already exists (use --force to overwrite)")
		}
	}

	// Apply defaults to ensure config is complete
	j.config.ApplyDefaults()

	// Generate configuration
	err := generateGoReleaserConfig(j.config)
	if err != nil {
		j.config.State = domain.ConfigStateInvalid
		return fmt.Errorf("failed to generate GoReleaser config: %w", err)
	}

	// Transition to Generated state
	j.config.State = domain.ConfigStateGenerated

	j.logger.Info("GoReleaser configuration generated successfully")
	return nil
}

func (j *ConfigGenerationJob) Rollback(ctx context.Context) error {
	j.logger.Info("Rolling back GoReleaser configuration generation")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return ctx.Err()
	}

	// Remove generated config
	if _, err := os.Stat(".goreleaser.yaml"); err == nil {
		// Check if backup exists
		if _, err := os.Stat(".goreleaser.yaml.backup"); err == nil {
			// Restore backup
			err := os.Rename(".goreleaser.yaml.backup", ".goreleaser.yaml")
			if err != nil {
				j.logger.Errorf("Failed to restore backup: %v", err)
				return err
			}
			j.logger.Info("Restored backup configuration")
		} else {
			// Remove generated file
			err := os.Remove(".goreleaser.yaml")
			if err != nil {
				j.logger.Errorf("Failed to remove generated config: %v", err)
				return err
			}
			j.logger.Info("Removed generated configuration")
		}
	}

	return nil
}

// GitHubActionsGenerationJob generates GitHub Actions workflow
type GitHubActionsGenerationJob struct {
	id     string
	config *domain.SafeProjectConfig
	logger *log.Logger
}

// NewGitHubActionsGenerationJob creates a new GitHub Actions generation job
func NewGitHubActionsGenerationJob(config *domain.SafeProjectConfig, logger *log.Logger) *GitHubActionsGenerationJob {
	return &GitHubActionsGenerationJob{
		id:     "github-actions-generation",
		config: config,
		logger: logger,
	}
}

func (j *GitHubActionsGenerationJob) ID() string {
	return j.id
}

func (j *GitHubActionsGenerationJob) Name() string {
	return "Generate GitHub Actions Workflow"
}

func (j *GitHubActionsGenerationJob) Execute(ctx context.Context) error {
	j.logger.Info("Generating GitHub Actions workflow")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return ctx.Err()
	}

	// Check if GitHub Actions is enabled
	if !j.config.GetGenerateActions() {
		j.logger.Info("GitHub Actions generation is disabled, skipping")
		return nil
	}

	// Create .github/workflows directory
	workflowDir := ".github/workflows"
	err := os.MkdirAll(workflowDir, 0o755)
	if err != nil {
		return fmt.Errorf("failed to create workflow directory: %w", err)
	}

	// Generate workflow
	err = generateGitHubActions(j.config)
	if err != nil {
		return fmt.Errorf("failed to generate GitHub Actions workflow: %w", err)
	}

	j.logger.Info("GitHub Actions workflow generated successfully")
	return nil
}

func (j *GitHubActionsGenerationJob) Rollback(ctx context.Context) error {
	j.logger.Info("Rolling back GitHub Actions workflow generation")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return ctx.Err()
	}

	// Remove generated workflow
	workflowPath := filepath.Join(".github", "workflows", "release.yml")
	if _, err := os.Stat(workflowPath); err == nil {
		err := os.Remove(workflowPath)
		if err != nil {
			j.logger.Errorf("Failed to remove generated workflow: %v", err)
			return err
		}
		j.logger.Info("Removed generated workflow")
	}

	// Try to remove .github directory if empty
	workflowDir := filepath.Join(".github", "workflows")
	workflowFiles, err := filepath.Glob(filepath.Join(workflowDir, "*.yml"))
	if err == nil && len(workflowFiles) == 0 {
		os.Remove(workflowDir)
		os.Remove(".github")
		j.logger.Info("Removed empty .github directory")
	}

	return nil
}

// ProjectValidationJob validates project structure
type ProjectValidationJob struct {
	id         string
	projectDir string
	logger     *log.Logger
}

// NewProjectValidationJob creates a new project validation job
func NewProjectValidationJob(projectDir string, logger *log.Logger) *ProjectValidationJob {
	return &ProjectValidationJob{
		id:         "project-validation",
		projectDir: projectDir,
		logger:     logger,
	}
}

func (j *ProjectValidationJob) ID() string {
	return j.id
}

func (j *ProjectValidationJob) Name() string {
	return "Validate Project Structure"
}

func (j *ProjectValidationJob) Execute(ctx context.Context) error {
	j.logger.Info("Validating project structure")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return ctx.Err()
	}

	// Check if project directory exists
	if _, err := os.Stat(j.projectDir); os.IsNotExist(err) {
		return fmt.Errorf("project directory does not exist: %s", j.projectDir)
	}

	// Check for go.mod
	goModPath := filepath.Join(j.projectDir, "go.mod")
	if _, err := os.Stat(goModPath); os.IsNotExist(err) {
		return fmt.Errorf("go.mod not found in project directory")
	}

	// Check for main package
	mainPaths := []string{
		filepath.Join(j.projectDir, "main.go"),
		filepath.Join(j.projectDir, "cmd", "*", "main.go"),
	}

	var mainFound bool
	for _, mainPath := range mainPaths {
		matches, err := filepath.Glob(mainPath)
		if err == nil && len(matches) > 0 {
			mainFound = true
			break
		}
	}

	if !mainFound {
		return fmt.Errorf("no main.go found in project (expected at main.go or cmd/*/main.go)")
	}

	j.logger.Info("Project structure validation passed")
	return nil
}

func (j *ProjectValidationJob) Rollback(ctx context.Context) error {
	// Validation job doesn't create any files, so rollback is a no-op
	j.logger.Info("Project validation rollback is a no-op")
	return nil
}

// DependencyCheckJob checks for required dependencies
type DependencyCheckJob struct {
	id           string
	dependencies []string
	logger       *log.Logger
}

// NewDependencyCheckJob creates a new dependency check job
func NewDependencyCheckJob(dependencies []string, logger *log.Logger) *DependencyCheckJob {
	return &DependencyCheckJob{
		id:           "dependency-check",
		dependencies: dependencies,
		logger:       logger,
	}
}

func (j *DependencyCheckJob) ID() string {
	return j.id
}

func (j *DependencyCheckJob) Name() string {
	return "Check Dependencies"
}

func (j *DependencyCheckJob) Execute(ctx context.Context) error {
	j.logger.Info("Checking dependencies")

	// Check if context is cancelled
	if ctx.Err() != nil {
		return ctx.Err()
	}

	var missingDeps []string

	for _, dep := range j.dependencies {
		path, err := exec.LookPath(dep)
		if err != nil {
			missingDeps = append(missingDeps, dep)
			j.logger.Warnf("Dependency not found: %s", dep)
		} else {
			j.logger.Debugf("Found dependency: %s at %s", dep, path)
		}
	}

	if len(missingDeps) > 0 {
		return fmt.Errorf("missing dependencies: %v", missingDeps)
	}

	j.logger.Info("All dependencies are available")
	return nil
}

func (j *DependencyCheckJob) Rollback(ctx context.Context) error {
	// Dependency check doesn't modify state, so rollback is a no-op
	j.logger.Info("Dependency check rollback is a no-op")
	return nil
}

// JobFactory creates jobs for common wizard operations
type JobFactory struct {
	logger *log.Logger
}

// NewJobFactory creates a new job factory
func NewJobFactory(logger *log.Logger) *JobFactory {
	return &JobFactory{
		logger: logger,
	}
}

// CreateFullWizardJobs creates all jobs for a complete wizard operation
func (jf *JobFactory) CreateFullWizardJobs(config *ProjectConfig, force bool) []Job {
	var jobs []Job

	// Convert to domain.SafeProjectConfig since ProjectConfig is an alias
	safeConfig := (*domain.SafeProjectConfig)(config)

	// Add project validation job
	jobs = append(jobs, NewProjectValidationJob(".", jf.logger))

	// Add dependency check job
	dependencies := []string{"go"}
	if safeConfig.GetDockerEnabled() {
		dependencies = append(dependencies, "docker")
	}
	// Only require cosign for advanced signing levels (basic can work without installation)
	if safeConfig.SigningLevel == domain.SigningLevelAdvanced || safeConfig.SigningLevel == domain.SigningLevelEnterprise {
		dependencies = append(dependencies, "cosign")
	}
	jobs = append(jobs, NewDependencyCheckJob(dependencies, jf.logger))

	// Add config generation job
	jobs = append(jobs, NewConfigGenerationJob(safeConfig, force, jf.logger))

	// Add GitHub Actions generation job
	if safeConfig.GetGenerateActions() {
		jobs = append(jobs, NewGitHubActionsGenerationJob(safeConfig, jf.logger))
	}

	return jobs
}

// prepareGoReleaserData prepares template data for GoReleaser configuration
func prepareGoReleaserData(config *domain.SafeProjectConfig) map[string]any {
	// Get version info
	version := getVersion()

	data := map[string]any{
		"ProjectName": config.ProjectName,
		"BinaryName":  config.BinaryName,
		"MainPath":    config.MainPath,
		"Version":     version,
		"Tag":         version,
		"Major":       getMajorVersion(version),
		"Date":        getCurrentDate(),
		"FullCommit":  getCommitHash(),
		"CGOEnabled": map[domain.CGOStatus]string{
			domain.CGOStatusDisabled: "0",
			domain.CGOStatusEnabled:  "1",
			domain.CGOStatusRequired: "1",
		}[config.CGOStatus],
		"DockerEnabled":  config.DockerSupport.IsEnabled(),
		"SigningEnabled": config.SigningLevel.IsEnabled(),

		// Environment variables for GitHub integration
		"Env": map[string]string{
			"GITHUB_OWNER": getGitHubOwner(),
			"GITHUB_REPO":  getGitHubRepo(),
		},

		// Platform/Arch combinations for archive naming
		"Os":   "{{.Os}}",   // This gets replaced in the template loop
		"Arch": "{{.Arch}}", // This gets replaced in the template loop
	}

	// Convert platforms
	if len(config.Platforms) > 0 {
		platforms := make([]string, len(config.Platforms))
		for i, platform := range config.Platforms {
			platforms[i] = string(platform) // Use raw constant value
		}
		data["Platforms"] = platforms
	}

	// Convert architectures
	if len(config.Architectures) > 0 {
		architectures := make([]string, len(config.Architectures))
		for i, arch := range config.Architectures {
			architectures[i] = string(arch) // Use raw constant value
		}
		data["Architectures"] = architectures
	}

	// Convert build tags
	if len(config.BuildTags) > 0 {
		tags := make([]string, len(config.BuildTags))
		for i, tag := range config.BuildTags {
			tags[i] = tag.String()
		}
		data["BuildTags"] = tags
	}

	// Add ignore combinations (common ones)
	data["IgnoreCombinations"] = []map[string]string{
		{"GoOS": "darwin", "GoArch": "386"},
		{"GoOS": "windows", "GoArch": "arm64"},
	}

	// Add Docker configuration if enabled
	if config.DockerSupport.IsEnabled() {
		data["DockerRegistry"] = config.DockerRegistry.String()
		data["DockerImage"] = config.GetDockerImageName()
	}

	return data
}

// prepareGitHubActionsData prepares template data for GitHub Actions workflow
func prepareGitHubActionsData(config *domain.SafeProjectConfig) map[string]any {
	data := map[string]any{
		"ProjectName":    config.ProjectName,
		"DockerEnabled":  config.DockerSupport.IsEnabled(),
		"SigningEnabled": config.SigningLevel.IsEnabled(),
	}

	// Convert action triggers to GitHub patterns
	if len(config.ActionsOn) > 0 {
		triggers := make([]string, len(config.ActionsOn))
		for i, trigger := range config.ActionsOn {
			triggers[i] = trigger.GitHubPattern()
		}
		data["Triggers"] = triggers
	}

	// Add Docker configuration if enabled
	if config.DockerSupport.IsEnabled() {
		data["DockerRegistry"] = config.DockerRegistry.String()
		data["DockerImage"] = config.GetDockerImageName()
	}

	return data
}

// CreateConfigOnlyJobs creates jobs for config generation only
func (jf *JobFactory) CreateConfigOnlyJobs(config *ProjectConfig, force bool) []Job {
	// Convert to domain.SafeProjectConfig since ProjectConfig is an alias
	safeConfig := (*domain.SafeProjectConfig)(config)

	return []Job{
		NewProjectValidationJob(".", jf.logger),
		NewConfigGenerationJob(safeConfig, force, jf.logger),
	}
}

// CreateValidationOnlyJob creates a validation-only job
func (jf *JobFactory) CreateValidationOnlyJob(projectDir string) Job {
	return NewProjectValidationJob(projectDir, jf.logger)
}

// Helper functions for template data

// getVersion gets the current version from git or fallback
func getVersion() string {
	// Try to get version from git
	if cmd := exec.Command("git", "describe", "--tags", "--always", "--dirty"); cmd != nil {
		if output, err := cmd.Output(); err == nil {
			if version := strings.TrimSpace(string(output)); version != "" {
				return version
			}
		}
	}

	// Fallback to version from build-time variable
	if version != "dev" {
		return version
	}

	// Final fallback
	return "v0.1.0"
}

// getMajorVersion extracts major version from version string
func getMajorVersion(version string) string {
	if strings.HasPrefix(version, "v") {
		version = version[1:]
	}
	parts := strings.Split(version, ".")
	if len(parts) > 0 {
		return parts[0]
	}
	return "0"
}

// getCurrentDate returns current date in YYYY-MM-DD format
func getCurrentDate() string {
	return time.Now().Format("2006-01-02")
}

// getCommitHash gets the current git commit hash
func getCommitHash() string {
	if cmd := exec.Command("git", "rev-parse", "HEAD"); cmd != nil {
		if output, err := cmd.Output(); err == nil {
			if hash := strings.TrimSpace(string(output)); hash != "" {
				return hash
			}
		}
	}
	return "unknown"
}

// getGitHubOwner tries to get GitHub owner from git remote
func getGitHubOwner() string {
	if cmd := exec.Command("git", "remote", "get-url", "origin"); cmd != nil {
		if output, err := cmd.Output(); err == nil {
			remote := strings.TrimSpace(string(output))
			// Parse GitHub URL: git@github.com:owner/repo.git or https://github.com/owner/repo.git
			if strings.Contains(remote, "github.com") {
				parts := strings.Split(remote, "github.com")
				if len(parts) > 1 {
					repoPath := strings.TrimPrefix(parts[1], ":")
					repoPath = strings.TrimPrefix(repoPath, "/")
					repoPath = strings.TrimSuffix(repoPath, ".git")
					pathParts := strings.Split(repoPath, "/")
					if len(pathParts) > 0 {
						return pathParts[0]
					}
				}
			}
		}
	}
	return "owner" // fallback
}

// getGitHubRepo tries to get GitHub repo from git remote
func getGitHubRepo() string {
	if cmd := exec.Command("git", "remote", "get-url", "origin"); cmd != nil {
		if output, err := cmd.Output(); err == nil {
			remote := strings.TrimSpace(string(output))
			// Parse GitHub URL: git@github.com:owner/repo.git or https://github.com/owner/repo.git
			if strings.Contains(remote, "github.com") {
				parts := strings.Split(remote, "github.com")
				if len(parts) > 1 {
					repoPath := strings.TrimPrefix(parts[1], ":")
					repoPath = strings.TrimPrefix(repoPath, "/")
					repoPath = strings.TrimSuffix(repoPath, ".git")
					pathParts := strings.Split(repoPath, "/")
					if len(pathParts) > 1 {
						return pathParts[1]
					}
				}
			}
		}
	}
	return "repo" // fallback
}
