package main

import (
	"fmt"
	"os"
)

// File permissions.
const (
	configFilePermission = 0o644 // rw-r--r-- for files
)

// printFix prints a success message and increments the fixed counter.
func printFix(message string, fixed *int) {
	fmt.Println(successStyle.Render(message))

	*fixed++
}

// attemptFixes attempts to fix common issues.
func attemptFixes(results *ValidationResults) {
	fmt.Println("🔧 Attempting to fix common issues...")
	fmt.Println()

	fixed := 0

	// Fix missing configuration directory
	if !results.ConfigExists {
		err := os.MkdirAll(".github/workflows", workflowDirPermission)
		if err == nil {
			printFix("✅ Created .github/workflows directory", &fixed)
		}
	}

	// Try to create basic configuration if missing
	if !results.ConfigExists {
		configContent := generateBasicConfig()

		err := os.WriteFile(goreleaserConfigFilename, []byte(configContent), configFilePermission)
		if err == nil {
			printFix("✅ Created basic .goreleaser.yaml", &fixed)
		}
	}

	if fixed > 0 {
		fmt.Println()
		fmt.Println(successStyle.Render(fmt.Sprintf("✅ Fixed %d issues", fixed)))
		fmt.Println(infoStyle.Render("💡 Run validation again to check remaining issues"))
	} else {
		fmt.Println(infoStyle.Render("ℹ️  No auto-fixable issues found"))
	}
}

// generateBasicConfig generates a basic GoReleaser configuration.
func generateBasicConfig() string {
	return `# Basic GoReleaser configuration
# Generated by GoReleaser Wizard

# The project name
project_name: my-project

# The build configuration
builds:
  - env:
     - CGO_ENABLED=0
   goos:
     - linux
     - darwin
     - windows
   goarch:
     - amd64
     - arm64

# Archive configuration
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

# Release configuration
release:
  github:
    owner: your-username
    name: my-project
`
}
