package main

import (
	"fmt"
	"os"
)

// attemptFixes attempts to fix common issues.
func attemptFixes(results *ValidationResults) error {
	fmt.Println("🔧 Attempting to fix common issues...")
	fmt.Println()

	fixed := 0

	// Fix missing configuration directory
	if !results.ConfigExists {
		if err := os.MkdirAll(".github/workflows", 0o755); err == nil {
			fmt.Println(successStyle.Render("✅ Created .github/workflows directory"))
			fixed++
		}
	}

	// Try to create basic configuration if missing
	if !results.ConfigExists {
		configContent := generateBasicConfig()
		if err := os.WriteFile(".goreleaser.yaml", []byte(configContent), 0o644); err == nil {
			fmt.Println(successStyle.Render("✅ Created basic .goreleaser.yaml"))
			fixed++
		}
	}

	if fixed > 0 {
		fmt.Println()
		fmt.Println(successStyle.Render(fmt.Sprintf("✅ Fixed %d issues", fixed)))
		fmt.Println(infoStyle.Render("💡 Run validation again to check remaining issues"))
	} else {
		fmt.Println(infoStyle.Render("ℹ️  No auto-fixable issues found"))
	}

	return nil
}

// generateBasicConfig generates a basic GoReleaser configuration.
func generateBasicConfig() string {
	return `# Basic GoReleaser configuration
# Generated by GoReleaser Wizard

# The project name
project_name: my-project

# The build configuration
builds:
  - env:
     - CGO_ENABLED=0
   goos:
     - linux
     - darwin
     - windows
   goarch:
     - amd64
     - arm64

# Archive configuration
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

# Release configuration
release:
  github:
    owner: your-username
    name: my-project
`
}
