# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Go modules dependency updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "LarsArtmann"
    assignees:
      - "LarsArtmann"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "automated"
    # Group minor and patch updates together
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Allow auto-merge for patch updates of trusted packages
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
    ignore:
      # Ignore major version updates for stability
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "LarsArtmann"
    assignees:
      - "LarsArtmann"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker dependency updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "LarsArtmann"
    assignees:
      - "LarsArtmann"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    # Only security updates for Docker to avoid frequent base image changes
    allow:
      - dependency-type: "direct"
        update-type: "security"

# Global settings for all ecosystems
registries: {}

# Dependabot will automatically:
# 1. Check for updates weekly on specified days
# 2. Create pull requests with conventional commit messages
# 3. Assign reviewers and labels
# 4. Group related updates together to reduce noise
# 5. Focus on security updates for Docker images
# 6. Ignore major version updates unless they are security fixes