version: "2"
run:
    timeout: 5m
    go: "1.25"
    build-tags: []
    modules-download-mode: readonly
    allow-parallel-runners: true
    allow-serial-runners: false
    issues-exit-code: 1
    tests: true
output:
    formats: {}
linters:
    enable:
        - zerologlint
        - importas
        - usestdlibvars
        - exhaustive
        - copyloopvar
        - unparam
        - musttag
        - godox
        - nolintlint
        - dogsled
        - maintidx
        - godoclint
        - unqueryvet
        - noctx
        - gocognit
        - gochecksumtype
        - errcheck
        - cyclop
        - err113
        - staticcheck
        - contextcheck
        - testifylint
        - nilnil
        - grouper
        - promlinter
        - errchkjson
        - unused
        - nestif
        - errorlint
        - whitespace
        - recvcheck
        - ireturn
        - rowserrcheck
        - mnd
        - nilnesserr
        - containedctx
        - wsl_v5
        - exptostd
        - goconst
        - misspell
        - noinlineerr
        - nonamedreturns
        - makezero
        - dupl
        - modernize
        - gomodguard
        - govet
        - thelper
        - exhaustruct
        - gochecknoinits
        - dupword
        - interfacebloat
        - nlreturn
        - reassign
        - ineffassign
        - gosmopolitan
        - godot
        - tparallel
        - varnamelen
        - goprintffuncname
        - forbidigo
        - paralleltest
        - nakedret
        - gochecknoglobals
        - goheader
        - testpackage
        - tagalign
        - iotamixing
        - protogetter
        - inamedparam
        - asciicheck
        - gocheckcompilerdirectives
        - prealloc
        - nosprintfhostport
        - funlen
        - bidichk
        - nilerr
        - gomoddirectives
        - spancheck
        - mirror
        - usetesting
        - errname
        - durationcheck
        - testableexamples
        - intrange
        - unconvert
        - gocyclo
        - gocritic
        - asasalint
        - loggercheck
        - wastedassign
        - sloglint
        - wrapcheck
        - predeclared
        - embeddedstructfieldcheck
        - iface
        - decorder
        - perfsprint
        - fatcontext
        - funcorder
        - ginkgolinter
        - depguard
        - forcetypeassert
        - canonicalheader
        - sqlclosecheck
        - bodyclose
        - tagliatelle
        - arangolint
        - gosec
        - revive
formatters:
    enable:
        - golines
issues: {}
