version: "2"

run:
  timeout: 5m
  go: "1.25"
  modules-download-mode: readonly
  allow-parallel-runners: true
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused
    - gosec
    - gocritic
    - misspell
    - dupl
    - goconst
    - predeclared
    - unconvert
    - wastedassign
    - errorlint
    - errname
    - copyloopvar
    - intrange
    - usestdlibvars
    - testifylint
    - thelper
    - gocyclo
    - funlen
    - cyclop
    - revive
    - whitespace
    - nlreturn
    - godot
    - makezero
    - nakedret
    - reassign
    - dogsled
    - durationcheck
    - asciicheck

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: var-naming
          disabled: true
        - name: increment-decrement
          disabled: true
        - name: indent-error-flow
          disabled: true
        - name: empty-block
          disabled: true
        - name: redefines-builtin-id
          disabled: true
        - name: context-as-argument
          disabled: true
        - name: receiver-naming
          disabled: true
        - name: early-return
          disabled: true
        - name: identical-ifelseif-branches
          disabled: true

    cyclop:
      max-complexity: 25

    funlen:
      lines: 350
      statements: 150

    goconst:
      min-len: 5
      min-occurrences: 6

    gocritic:
      disabled-checks:
        - ifElseChain

    gosec:
      excludes:
        - G304
        - G306
        - G301
        - G117
        - G204

  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst
          - funlen
          - gocyclo
          - cyclop
          - gocritic
          - revive
          - errcheck
          - thelper
          - unconvert
          - unused

      - path: '.*\.generated\.go$'
        linters:
          - all

      - linters:
          - godot
        source: '^(//|/\*) .*TODO|FIXME|BUG|NOTE|HACK'

    paths:
      - vendor
      - third_party
      - testdata
      - examples
      - internal/mock
      - ".*\\.pb\\.go$"
      - ".*\\.gen\\.go$"

formatters:
  enable: []
