package templates

// GoReleaserTemplate is the GoReleaser configuration template.
const GoReleaserTemplate = `# GoReleaser configuration
# Generated by goreleaser-wizard
# https://goreleaser.com

version: 2

project_name: {{.ProjectName}}

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...

builds:
  - id: {{.BinaryName}}
    main: {{.MainPath}}
    binary: {{.BinaryName}}
    
    env:
      - CGO_ENABLED={{.CGOEnabled}}
    
    goos:
{{range .Platforms}}      - {{.}}
{{end}}
    goarch:
{{range .Architectures}}      - {{.}}
{{end}}
{{if .IgnoreCombinations}}
    # Ignore certain platform combinations
    ignore:
{{range .IgnoreCombinations}}      - goos: {{.GoOS}}
        goarch: {{.GoArch}}
{{end}}{{end}}
{{if .BuildTags}}
    # Build tags for pure Go builds
    tags:
{{range .BuildTags}}      - {{.}}
{{end}}{{end}}

archives:
  - id: default
    name_template: "{{"{{"}}.ProjectName{{"}}"}}_{{"{{"}}.Version{{"}}"}}_{{"{{"}}.Os{{"}}"}}_{{"{{"}}.Arch{{"}}"}}"
    
    format_overrides:
      - goos: windows
        format: zip
    
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{"{{"}}"incpatch .Version{{"}}"}}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "{{"{{"}}.Env.GITHUB_OWNER{{"}}"}}"
    name: "{{"{{"}}.Env.GITHUB_REPO{{"}}"}}"
  
  draft: false
  prerelease: auto
  mode: append
  
  footer: |
    ## Installation
    Download the appropriate archive for your platform from the assets below.

{{if .DockerEnabled}}
dockers:
  - image_templates:
      - "{{.DockerRegistry}}/{{.DockerImage}}:{{"{{"}}.Tag{{"}}"}}"
      - "{{.DockerRegistry}}/{{.DockerImage}}:v{{"{{"}}.Major{{"}}"}}"
      - "{{.DockerRegistry}}/{{.DockerImage}}:latest"
    
    dockerfile: Dockerfile
    
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{"{{"}}.Date{{"}}"}}"
      - "--label=org.opencontainers.image.title={{"{{"}}.ProjectName{{"}}"}}"
      - "--label=org.opencontainers.image.revision={{"{{"}}.FullCommit{{"}}"}}"
      - "--label=org.opencontainers.image.version={{"{{"}}.Version{{"}}"}}"
      - "--platform=linux/amd64"
{{end}}`

// GitHubActionsTemplate is the GitHub Actions workflow template.
const GitHubActionsTemplate = `name: Release

on:
[[range .Triggers]]  [[.]]
[[end]]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
[[if .DockerEnabled]]
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: [[.DockerRegistry]]
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
[[end]][[if .SigningEnabled]]
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
[[end]]
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}`

// DockerfileTemplate is the Dockerfile template.
const DockerfileTemplate = `# Dockerfile for {{.ProjectName}}
# Generated by goreleaser-wizard

# Build stage
FROM golang:{{.GoVersion}}-alpine AS builder

# Install git (needed for go modules)
RUN apk add --no-cache git ca-certificates tzdata

# Set working directory
WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED={{.CGOEnabled}} GOOS={{.TargetOS}} GOARCH={{.TargetArch}} go build \
    -ldflags='{{.LDFlags}}' \
    -a -installsuffix cgo \
    -o main {{.MainPath}}

# Final stage
FROM alpine:{{.AlpineVersion}}

# Install ca-certificates for HTTPS requests
RUN apk --no-cache add ca-certificates tzdata

# Create non-root user
RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup

# Set working directory
WORKDIR /root/

# Copy binary from builder
COPY --from=builder /app/main .
{{if .ConfigFiles}}
# Copy config files
{{range .ConfigFiles}}
COPY {{.}} .
{{end}}
{{end}}

# Change ownership to non-root user
RUN chown -R appuser:appgroup .

# Switch to non-root user
USER appuser

# Expose port
{{if .ExposePort}}
EXPOSE {{.ExposePort}}
{{end}}

# Set environment variables
{{range .EnvVars}}
ENV {{.Key}}={{.Value}}
{{end}}

# Health check
{{if .HealthCheck}}
HEALTHCHECK --interval={{.HealthCheck.Interval}} --timeout={{.HealthCheck.Timeout}} --start-period={{.HealthCheck.StartPeriod}} --retries={{.HealthCheck.Retries}} \
{{range .HealthCheck.Commands}}  {{.}} \
{{end}}
{{end}}

# Set entrypoint
ENTRYPOINT ["./main"]

# Default arguments
CMD ["--help"]`

// HomebrewTemplate is the Homebrew formula template.
const HomebrewTemplate = `class {{.FormulaName}} < Formula
  desc "{{.ProjectDescription}}"
  homepage "{{.Homepage}}"
  url "{{.ArchiveURL}}"
  sha256 "{{.Checksum}}"
  license "{{.License}}"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "{{.LDFlags}}"), "{{.MainPath}}"
  end

  test do
    assert_match "{{.TestOutput}}", shell_output("#{bin}/{{.BinaryName}} --version")
  end
{{if .Service}}
  
  service do
    run [opt_bin/"{{.BinaryName}}"]
    keep_alive true
    working_dir var
    log_path var/"log/{{.BinaryName}}.log"
    error_log_path var/"log/{{.BinaryName}}.error.log"
  end
{{end}}
end`
