package templates

// Templates embedded at build time. This package is the single source of
// truth for everything the wizard renders; jobs must not keep private copies.

// GoReleaserTemplate is the GoReleaser v2.17 configuration template. It
// renders a config that passes `goreleaser check` with zero deprecations
// and no environment variables; owner/repo are detected at generate time.
const GoReleaserTemplate = `# GoReleaser configuration
# Generated by goreleaser-wizard
# https://goreleaser.com

version: 2

project_name: {{.ProjectName}}

before:
  hooks:
    - go mod tidy

builds:
  - id: {{.BinaryName}}
    main: {{.MainPath}}
    binary: {{.BinaryName}}
    
    env:
      - CGO_ENABLED={{.CGOEnabled}}
    
    goos:
{{range .Platforms}}      - {{.}}
{{end}}
    goarch:
{{range .Architectures}}      - {{.}}
{{end}}
{{if .IgnoreCombinations}}
    # Ignore certain platform combinations
    ignore:
{{range .IgnoreCombinations}}      - goos: {{.GoOS}}
        goarch: {{.GoArch}}
{{end}}{{end}}
{{if .BuildTags}}
    # Build tags for pure Go builds
    tags:
{{range .BuildTags}}      - {{.}}
{{end}}{{end}}

archives:
  - id: default
    name_template: "{{"{{"}}.ProjectName{{"}}"}}_{{"{{"}}.Version{{"}}"}}_{{"{{"}}.Os{{"}}"}}_{{"{{"}}.Arch{{"}}"}}"
    
    format_overrides:
      - goos: windows
        formats: [zip]
    
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{"{{"}}incpatch .Version{{"}}"}}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "{{.GitHubOwner}}"
    name: "{{.GitHubRepo}}"

  draft: false
  prerelease: auto

  footer: |
    ## Installation
    Download the appropriate archive for your platform from the assets below.

{{if .DockerEnabled}}
dockers_v2:
  - id: {{.BinaryName}}
    images:
      - "{{.DockerRegistry}}/{{.DockerImage}}"

    tags:
      - "{{"{{"}}.Tag{{"}}"}}"
      - "v{{"{{"}}.Major{{"}}"}}"
      - "{{"{{"}}if not .IsNightly{{"}}"}}latest{{"{{"}}end{{"}}"}}"

    dockerfile: Dockerfile

    platforms:
{{range .DockerPlatforms}}      - {{.}}
{{end}}
    annotations:
      org.opencontainers.image.created: "{{"{{"}}.Date{{"}}"}}"
      org.opencontainers.image.title: "{{"{{"}}.ProjectName{{"}}"}}"
      org.opencontainers.image.revision: "{{"{{"}}.FullCommit{{"}}"}}"
      org.opencontainers.image.version: "{{"{{"}}.Version{{"}}"}}"
{{end}}
`

// GitHubActionsTemplate is the GitHub Actions release workflow template.
// It uses [[ ]] delimiters to avoid clashing with GitHub expression syntax.
const GitHubActionsTemplate = `name: Release

on:
[[range .Triggers]]  [[.]]
[[end]]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
[[if .DockerEnabled]]
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: [[.DockerRegistry]]
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
[[end]][[if .SigningEnabled]]
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
[[end]]
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`

// DockerfileTemplate renders a Dockerfile for use with dockers_v2.
// GoReleaser copies the prebuilt binaries of each target platform into the
// build context under $TARGETPLATFORM, so the Dockerfile must COPY them
// instead of rebuilding (see goreleaser dockers_v2 docs).
const DockerfileTemplate = `# Dockerfile for {{.ProjectName}}
# Generated by goreleaser-wizard
# Copy the binaries prebuilt by GoReleaser - never rebuild them here.

FROM {{.BaseImage}}
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/{{.BinaryName}} /usr/bin/{{.BinaryName}}
{{if .ExposePort}}
EXPOSE {{.ExposePort}}
{{end}}
ENTRYPOINT ["/usr/bin/{{.BinaryName}}"]
`

// HomebrewTemplate is the Homebrew formula template.
const HomebrewTemplate = `class {{.FormulaName}} < Formula
  desc "{{.ProjectDescription}}"
  homepage "{{.Homepage}}"
  url "{{.ArchiveURL}}"
  sha256 "{{.Checksum}}"
  license "{{.License}}"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "{{.LDFlags}}"), "{{.MainPath}}"
  end

  test do
    assert_match "{{.TestOutput}}", shell_output("#{bin}/{{.BinaryName}} --version")
  end
{{if .Service}}
  
  service do
    run [opt_bin/"{{.BinaryName}}"]
    keep_alive true
    working_dir var
    log_path var/"log/{{.BinaryName}}.log"
    error_log_path var/"log/{{.BinaryName}}.error.log"
  end
{{end}}
end`
